version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: zidan
      POSTGRES_PASSWORD: Xymwq12KK
      POSTGRES_DB: nest
    networks:
      - cobanest
networks:
  cobanest:
